### ISSUE TITLE
AttributeError: 'Legend' object has no attribute 'legendHandles'. Did you mean: 'legend_handles'? 

### ISSUE THREAD

**Issue by hrj21** [TarikExner/CytoNormPy#1]
Hello! Thank you for creating this Python package. CytoNorm is a critical step in our R pipelines and now we finally have it in Python.

I'm following this plotting tutorial: https://cytonormpy.readthedocs.io/en/latest/vignettes/cnp_plotting.html

But this step:
```
fig = cnpl.histogram(file_name = files[3],
                     x_channel = "Nd142Di",
                     x_scale = "linear",
                     display_reference = True,
                     grid = "channels",
                     figsize = (20,20),
                     show = False,
                     return_fig = True)
```
gives me the error:
```
AttributeError: 'Legend' object has no attribute 'legendHandles'. Did you mean: 'legend_handles'?
```

Am I doing something wrong? I'm using cytonormpy 0.0.1 in Python 3.12.4.

Many thanks
Hefin

**Comment by TarikExner** [comment]
Hey!

Thanks for reporting!

I will get to it as soon as I can. Could you tell me the versions of matplotlib and seaborn that you are using?


Best,
Tarik

**Comment by hrj21** [comment]
Thanks for such a fast response. Sure, matplotlib version 3.9.1 and seaborn version 0.13.2.

Best wishes
Hefin

**Comment by TarikExner** [comment]
This was indeed about the matplotlib version. CytoNormPy uses the more generic (and not deprecated...) legend_handles attribute.

Best,
Tarik

**Comment by hrj21** [comment]
Hi Tarik, I've tried installing again using `pip install git+https://github.com/TarikExner/CytoNormPy@main`, but the version is still 0.0.1 and I'm getting the same error. Sorry, I'm not a regular Python user so I might be missing something.

**Comment by TarikExner** [comment]
All good, I will have a look into it; sorry for the premature closing..

Are you using conda or some other venv?

Best,
Tarik

**Comment by hrj21** [comment]
Yes I'm using conda (through VS code). Aha, I just tried it outside of that conda environment and it works now. Sorry, I reinstalled it inside the conda environment so I'm not quite sure why it wasn't working.

**Comment by TarikExner** [comment]
Okay, good to hear! So I mark this as solved?

Best,
Tarik

**Comment by hrj21** [comment]
Yes I think so thank you :)

**Comment by TarikExner** [comment]
Perfect! :) Thanks a lot for the quick replies and the bug report!
